### ISSUE TITLE
Arrays are not allowed in class constants

### ISSUE THREAD

**Issue by jpkeisala** [GuLinux/grav-plugin-flickr#1]
I just installed Flickr plugin to the default Grav installation and I am getting following error on Grav Admin.

Whoops
\Exception\ErrorException thrown with message "Arrays are not allowed in class constants"

Stacktrace:
#0 Whoops\Exception\ErrorException in /Users/jp/Code/temp/grav-admin/user/plugins/flickr/classes/FlickrCommons.php:13

**Comment by GuLinux** [comment]
Hi,
I committed a fix, could you please try it applying the patch [https://github.com/GuLinux/grav-plugin-flickr/commit/1e454b8491ba37ba4b5f787c33506a3bfa80e11e](https://github.com/GuLinux/grav-plugin-flickr/commit/1e454b8491ba37ba4b5f787c33506a3bfa80e11e)?

**Comment by jpkeisala** [comment]
Wow! that was fast fix. :)
Works now. Thanks for prompt fix.

**Comment by GuLinux** [comment]
Thank you for the report :)
Releasing a patch version then, and closing the issue.
