### ISSUE TITLE
When trying to add shortcode to a page DEFAULT_PARAMS on FlickrCommons throws runtime error

### ISSUE THREAD

**Issue by jpkeisala** [GuLinux/grav-plugin-flickr#2]
Whoops\Exception\ErrorException thrown with message "Undefined class constant 'DEFAULT_PARAMS'"

Stacktrace:
#0 Whoops\Exception\ErrorException in /Users/jp/Code/temp/grav-admin/user/plugins/flickr/shortcodes/FlickrPhotoShortcode.php:20

---

To reproduce the error try to add single photos, photosets (albums) and collections as described on the readme.md

**Comment by GuLinux** [comment]
Hi,
I think you're still using the old (1.0.5) version.
If you look the 1.0.6 file ([here](https://github.com/GuLinux/grav-plugin-flickr/blob/v1.0.6/shortcodes/FlickrPhotoShortcode.php)) you'll notice there is no "DEFAULT_PARAM" at line 20

**Comment by jpkeisala** [comment]
Yes, you were right. I updated the whole plugin.
